### PR TITLE
Removing private SSH key

### PR DESCRIPTION
**Pull request by oudeismetis**
I noticed you had commited a private ssh key to your repo. 

**"I know. It was intentional."** 
Sorry to bother you then. Feel free to ignore this PR. 
You know you can also [secure private data while keeping it under source control](https://keybase.io/blog/encrypted-git-for-everyone).

**"I didn't notice. What is this file? Is it a problem?"**
[This can be a very bad thing](http://www.securityweek.com/github-search-makes-easy-discovery-encryption-keys-passwords-source-code)

**"I keep accidentally typing `git add .`, any way I can prevent that from being an issue?"**
There are a couple of steps you should take immediately:
1. Avoid commands like `git add .` and `git add *`. It's better to be more explicit when you can.
1. Assume your key is compromised. Unassociate it from any accounts you are using it for and [generate a new key](https://help.github.com/articles/reviewing-your-ssh-keys/).
1. Store your keys in a location outside of your project.
1. Use a [.gitignore file](https://git-scm.com/docs/gitignore) to prevent accidental commits of certain files.

Github also has a page about how to [remove sensitive data from a repo](https://help.github.com/articles/removing-sensitive-data-from-a-repository/).

Hope this PR finds you well

### CODE REVIEW

**Comment by giper45** [comment]
Thanks very much Romano, I know and this was intentional: I use GitHub as technology to implement virtual environment for the study of network security; the application that manages them is DockerSecurityPlayground repo, while the DSP_LightPorject is the repository that contains labs, so that private key links to a ssh scenario. 
Good Morning and thanks again.
GP

**Comment by giper45** [comment]
Give a look to https://github.com/giper45/DockerSecurityPlayground ;)

**Comment by oudeismetis** [comment]
oh nice!
Yea this PR was opened by an automated tool I wrote that has been slowly finding repos and opening PRs.

I'm actually finding a decent number projects where the private key was intentionally added as a part of a docker/puppet/chef/ansible/etc architecture. I'm thinking about researching that a bit more and possibly writing a blog post on "When you SHOULD add private keys to Github and how to do it properly". 

Curious if you have any thoughts on that.

**Comment by giper45** [comment]
Well, it's a little strange request :) 
I think that you "could" add private keys to Github but if they are used in production they never should be sent on a GitHub repository... 
By design, a private key allows authentication, so it should be private and stored in a safe place, where nobody but you can access it, so it's fairly controversial to add it in a GitHub repository (even if this a private repository, you have to think in "evil mode", so what could be the risks if an attacker is able to access in my private GitHub repository?) 
When an application uses private keys, the application should be good designed about security, by setting into a config file a path to the private key and to any secret that it uses; this configuration file should be released as an example file (example.configuration.json for example) and in the documentation a description about how to use it should be provided (for example, cp example.configuration.json in configuration.json file and add the path where the "secret" is located). 

I think that private keys should be added in GitHub only for example scenarios, such as my virtual labs, where a user "simulates" an attacker, and has fully access to the virtual labs. 

Also for example scenarios, or testing purposes... anyway it' important to advise the user that the pair of public and private key never should be used in a production environment, and that these keys have been used only for educational purposes. 
Hope it can help you ;)
Regards,
G

**Comment by oudeismetis** [comment]
Very helpful!
Yea, most seem to have the excuse of "this is only used on an intranet or private network" or "This is only used for our build system with VMs talking to each other". They sound like plausible/reasonable reasons, but I hadn't thought too much about those scenarios until I wrote this bot. So now I'm on the hunt for best practices for that case where you "know" that the private key isn't usable on the public internet.

**Pull request closed without merging**
